import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { LayoutDashboard, Users, FileText, ReceiptText, Bot, Plus, MapPin, Search, Building2, ChevronRight, Sparkles, Send, X, FileSearch, Calculator } from 'lucide-react'
import { listAgentModels, askAgent } from '@/lib/agent.functions'
import { supabase } from '@/integrations/supabase/client'

export const Route = createFileRoute('/')({ component: Home })
const nav=[['Overview',LayoutDashboard],['Leads',Users],['Quotes',FileText],['Invoices',ReceiptText]] as const
const peso=(c:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format((c||0)/100)

function Home(){
 const[tab,setTab]=useState('Overview');const[agentOpen,setAgentOpen]=useState(true)
 const[leads,setLeads]=useState<any[]>([]),[quotes,setQuotes]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([])
 const load=async()=>{const[l,q,i]=await Promise.all([supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('quotes').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('invoices').select('*').order('created_at',{ascending:false}).limit(50)]);setLeads(l.data||[]);setQuotes(q.data||[]);setInvoices(i.data||[])}
 useEffect(()=>{load()},[])
 const due=invoices.reduce((s,x)=>s+Number(x.balance_centavos||0),0),pipeline=quotes.reduce((s,x)=>s+Number(x.total_centavos||0),0)
 return <div className={`min-h-screen bg-[#f6f8fb] text-[#14263d] lg:grid ${agentOpen?'lg:grid-cols-[238px_minmax(0,1fr)_365px]':'lg:grid-cols-[238px_minmax(0,1fr)]'}`}>
  <aside className="hidden min-h-screen flex-col bg-[#071a30] p-4 text-white lg:flex"><div className="border-b border-[#20344c] px-3 py-4 text-xl font-bold">Azarraga Glass</div><div className="px-3 pb-2 pt-6 text-[9px] font-bold tracking-[.18em] text-[#617891]">COMMERCIAL WORKSPACE</div><nav className="space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>setTab(n)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${tab===n?'bg-[#102d50] text-white':'text-[#9bacc0]'}`}><I size={17}/>{n}</button>)}</nav><div className="mt-auto border-t border-[#20344c] pt-4"><button onClick={()=>setAgentOpen(true)} className="flex items-center gap-3 p-2"><Bot size={18}/><span className="text-left"><b className="block text-xs">Azarraga Agent</b><small className="text-[#77d6ae]">● Ready to work</small></span></button><small className="block p-2 text-[#637991]">Puerto Princesa · Palawan</small></div></aside>
  <section className="min-w-0 p-4 sm:p-8"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><span className="text-[9px] font-extrabold tracking-[.16em] text-[#3972ae]">AZARRAGA COMMERCIAL AGENT / {tab.toUpperCase()}</span><h1 className="mt-1 text-3xl font-bold">{tab}</h1></div><div className="flex gap-2"><button onClick={()=>setAgentOpen(!agentOpen)} className="inline-flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm font-semibold"><Sparkles size={16}/>Agent</button><button onClick={()=>setTab('Quotes')} className="inline-flex items-center gap-2 rounded-lg bg-[#0b5daf] px-4 py-2 text-sm font-semibold text-white"><Plus size={16}/>New quote</button></div></header>
  {tab==='Overview'&&<><div className="flex min-h-[185px] flex-col justify-between rounded-2xl bg-gradient-to-br from-[#0b2543] to-[#0d3b69] p-8 text-white sm:flex-row sm:items-end"><div><span className="text-xs font-bold tracking-widest text-[#83b8ed]">AZARRAGA GLASS & ALUMINUM</span><h2 className="mt-3 text-3xl font-bold">Commercial workspace</h2><p className="mt-2 text-[#b8c7d8]">Find the customer. Quote the job. Get paid.</p></div><div className="mt-8 flex items-center gap-3 sm:mt-0"><MapPin/><div><b className="block">Palawan operations</b><span className="text-xs text-[#9db1c7]">Puerto Princesa · El Nido · San Vicente / Port Barton</span></div></div></div><div className="my-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Active leads" value={String(leads.length)} meta="Palawan opportunities"/><Stat label="Quotes in pipeline" value={peso(pipeline)} meta={`${quotes.length} quotations`}/><Stat label="Receivables" value={peso(due)} meta={`${invoices.length} billing records`}/><Stat label="Needs review" value={String(quotes.filter(q=>q.status!=='APPROVED').length)} meta="Human approval queue"/></div><div className="grid gap-3 xl:grid-cols-[1.7fr_1fr]"><Panel title="Needs your attention">{leads.slice(0,4).map(l=><Row key={l.id} icon={Building2} title={l.project||l.company||'Opportunity'} sub={`${l.location||'Palawan'} · ${l.next_action||'Review next action'}`} end={`${l.score||0}% fit`}/>)}{!leads.length&&<p className="py-8 text-sm text-slate-500">No leads yet. The database is connected and ready.</p>}</Panel><Panel title="What are we doing?"><Quick icon={Search} title="Find new business" sub="Research Palawan opportunities" onClick={()=>setTab('Leads')}/><Quick icon={FileText} title="Prepare a quotation" sub="Plans, measurements or request" onClick={()=>setTab('Quotes')}/><Quick icon={ReceiptText} title="Manage billing" sub="Drafts, payments and balances" onClick={()=>setTab('Invoices')}/><Quick icon={Bot} title="Ask the agent" sub="Use Azarraga commercial memory" onClick={()=>setAgentOpen(true)}/></Panel></div></>}
  {tab==='Leads'&&<Workspace eyebrow="FIND BUSINESS" title="Palawan lead pipeline" text="Research the opportunity, identify the decision maker and move toward one goal: send us the plans."><Table heads={['Opportunity','Location','Type','Stage','Next action','Fit']} rows={leads.map(l=>[l.project||'Opportunity',l.location||'—',l.project_type||'—',l.status||'—',l.next_action||'—',`${l.score||0}%`])}/></Workspace>}
  {tab==='Quotes'&&<Workspace eyebrow="WIN BUSINESS" title="Quotation workspace" text="The agent handles evidence. The quote engine handles arithmetic. You approve the commercial document."><Table heads={['Quote','Customer','Project','Status','Total','Review']} rows={quotes.map(q=>[q.quote_number||'Draft',q.customer_name||'—',q.project_name||'—',q.status||'DRAFT',peso(q.total_centavos),q.status==='APPROVED'?'Approved':'Human review'])}/></Workspace>}
  {tab==='Invoices'&&<Workspace eyebrow="BILL BUSINESS" title="Invoices & payments" text="Approved quotation data carries forward. Billing remains controlled by Azarraga."><Table heads={['Invoice','Customer','Project','Total','Balance','Status']} rows={invoices.map(i=>[i.invoice_number||'Draft',i.customer_name||'—',i.project_name||'—',peso(i.total_centavos),peso(i.balance_centavos),i.status||'DRAFT'])}/></Workspace>}
  </section>{agentOpen&&<Agent onClose={()=>setAgentOpen(false)}/>}</div>
}
function Stat({label,value,meta}:any){return <div className="rounded-xl border bg-white p-5"><span className="text-xs text-slate-500">{label}</span><strong className="my-2 block text-2xl text-[#123a63]">{value}</strong><small className="text-slate-500">{meta}</small></div>}
function Panel({title,children}:any){return <section className="rounded-xl border bg-white p-5"><small className="font-bold tracking-widest text-[#3972ae]">WORKSPACE</small><h3 className="mb-3 mt-1 text-lg font-bold">{title}</h3>{children}</section>}
function Row({icon:Icon,title,sub,end}:any){return <div className="grid grid-cols-[38px_1fr_auto] items-center gap-3 border-t py-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eef5fb] text-[#1766ad]"><Icon size={17}/></span><div><b className="block text-sm">{title}</b><small className="text-slate-500">{sub}</small></div><em className="text-xs font-bold not-italic text-[#1766ad]">{end}</em></div>}
function Quick({icon:Icon,title,sub,onClick}:any){return <button onClick={onClick} className="grid w-full grid-cols-[36px_1fr_auto] items-center gap-3 border-t py-3 text-left"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#eef5fb] text-[#1766ad]"><Icon size={16}/></span><div><b className="block text-sm">{title}</b><small className="text-slate-500">{sub}</small></div><ChevronRight size={15}/></button>}
function Workspace({eyebrow,title,text,children}:any){return <><div className="mb-3 rounded-xl border bg-white p-6"><small className="font-bold tracking-widest text-[#3972ae]">{eyebrow}</small><h2 className="mt-1 text-2xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>{children}</>}
function Table({heads,rows}:any){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{heads.map((h:string)=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((r:any[],i:number)=><tr key={i}>{r.map((v,j)=><td key={j} className="px-4 py-4">{v}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={heads.length} className="p-12 text-center text-slate-500">No records yet.</td></tr>}</tbody></table></div>}
function Agent({onClose}:any){const[models,setModels]=useState<any[]>([]),[model,setModel]=useState(''),[input,setInput]=useState(''),[messages,setMessages]=useState<any[]>([{role:'agent',text:'I’m ready. Ask about leads, quotes, invoices or commercial memory.'}]),[busy,setBusy]=useState(false);useEffect(()=>{listAgentModels().then((d:any)=>{const free=(d.models||[]).filter((m:any)=>m.free);setModels(free);if(free[0])setModel(free[0].id)}).catch(()=>{})},[]);const send=async()=>{if(!input.trim()||!model||busy)return;const text=input;setMessages(m=>[...m,{role:'user',text}]);setInput('');setBusy(true);try{const d:any=await askAgent({data:{message:text,model,intent:'general'}});setMessages(m=>[...m,{role:'agent',text:d.reply||d.error||'No response'}])}finally{setBusy(false)}};return <aside className="fixed inset-y-0 right-0 z-50 flex w-full max-w-[365px] flex-col border-l bg-white shadow-2xl lg:static lg:z-auto lg:shadow-none"><div className="grid grid-cols-[38px_1fr_auto] items-center gap-3 border-b p-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#0d3158] text-white"><Bot size={19}/></span><div><b className="block text-sm">Azarraga Agent</b><small className="text-emerald-700">● Commercial memory connected</small></div><button onClick={onClose}><X/></button></div><div className="p-4"><label className="text-xs font-bold">OPENROUTER FREE MODEL</label><select className="mt-2 w-full rounded-lg border p-2" value={model} onChange={e=>setModel(e.target.value)}><option value="">Select model</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><div className="grid grid-cols-2 gap-2 px-4">{[[FileSearch,'Review plans'],[Calculator,'Draft quote'],[Users,'Find leads'],[ReceiptText,'Billing']].map(([I,t]:any)=><button key={t} onClick={()=>setInput(t)} className="flex items-center gap-2 rounded-lg border p-2 text-xs"><I size={14}/>{t}</button>)}</div><div className="flex-1 overflow-auto p-4">{messages.map((m,i)=><div key={i} className={`mb-2 max-w-[88%] rounded-xl p-3 text-xs leading-5 ${m.role==='user'?'ml-auto bg-[#0d3158] text-white':'bg-slate-100'}`}>{m.text}</div>)}{busy&&<div className="rounded-xl bg-slate-100 p-3 text-xs">Working with ICM…</div>}</div><div className="grid grid-cols-[1fr_42px] gap-2 border-t p-3"><textarea value={input} onChange={e=>setInput(e.target.value)} className="resize-none rounded-lg border p-3 text-sm" placeholder="Ask the Azarraga Agent…"/><button onClick={send} className="rounded-lg bg-[#0b5daf] text-white"><Send size={17} className="mx-auto"/></button></div></aside>}
