import { createFileRoute } from '@tanstack/react-router'
import { useEffect,useState } from 'react'
import { LayoutDashboard,Users,FileText,ReceiptText,Bot,Plus,MapPin,Search,Building2,ChevronRight,Sparkles,Send,X,FileSearch,CheckCircle2,RefreshCw,ShoppingCart,Printer,Upload,LogOut } from 'lucide-react'
import { listAgentModels,askAgent } from '@/lib/agent.functions'
import { supabase } from '@/integrations/supabase/client'
import { createLeadWorkflow,createQuoteWorkflow,approveQuoteWorkflow,createPOWorkflow,createInvoiceWorkflow,recordPaymentWorkflow,uploadCommercialDocument,type QuoteDraft } from '@/lib/commercial-workflow'
import { QuoteBuilder } from '@/components/commercial/QuoteBuilder'
import { printCommercialDocument } from '@/lib/commercial-documents'

export const Route=createFileRoute('/')({component:Home})
const nav=[['Overview',LayoutDashboard],['Leads',Users],['Quotes',FileText],['Invoices',ReceiptText],['Documents',FileSearch]] as const
const peso=(c:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format((c||0)/100)

function Home(){const[session,setSession]=useState<any>(undefined);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:s}=supabase.auth.onAuthStateChange((_e,v)=>setSession(v));return()=>s.subscription.unsubscribe()},[]);if(session===undefined)return <Splash/>;if(!session)return <Login/>;return <WorkspaceApp/>}
function Splash(){return <div className="grid min-h-screen place-items-center bg-[#071a30] text-white"><div className="text-center"><b className="text-2xl">Azarraga Glass</b><p className="mt-2 text-sm text-slate-400">Connecting commercial workspace…</p></div></div>}
function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const login=async(e:any)=>{e.preventDefault();setBusy(true);setError('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)};const github=async()=>{setBusy(true);const{error}=await supabase.auth.signInWithOAuth({provider:'github',options:{redirectTo:window.location.origin}});if(error){setError(error.message);setBusy(false)}};return <div className="grid min-h-screen place-items-center bg-[#071a30] p-5"><form onSubmit={login} className="w-full max-w-md rounded-2xl bg-white p-7 shadow-2xl"><small className="font-bold tracking-[.16em] text-[#3972ae]">COMMERCIAL WORKSPACE</small><h1 className="mt-1 text-3xl font-bold text-[#14263d]">Azarraga Glass</h1><p className="mb-6 mt-2 text-sm text-slate-500">Sign in to access customers, quotations, invoices, documents and the Azarraga Agent.</p><Field label="Email" value={email} onChange={setEmail} type="email"/><div className="mt-3"><Field label="Password" value={password} onChange={setPassword} type="password"/></div>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-5 w-full rounded-lg bg-[#0F4C81] px-4 py-3 font-semibold text-white disabled:opacity-50">{busy?'Signing in…':'Sign in'}</button><button type="button" disabled={busy} onClick={github} className="mt-2 w-full rounded-lg border px-4 py-3 font-semibold text-[#14263d]">Sign in with GitHub</button></form></div>}

function WorkspaceApp(){
 const[tab,setTab]=useState('Overview'),[agentOpen,setAgentOpen]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[quoteOpen,setQuoteOpen]=useState(false),[modal,setModal]=useState<any>(null)
 const[leads,setLeads]=useState<any[]>([]),[quotes,setQuotes]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([]),[pos,setPos]=useState<any[]>([]),[docs,setDocs]=useState<any[]>([])
 const load=async()=>{const[l,q,i,p,d]=await Promise.all([supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('quotes').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('invoices').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('purchase_orders').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('client_documents').select('*').order('created_at',{ascending:false}).limit(50)]);setLeads(l.data||[]);setQuotes(q.data||[]);setInvoices(i.data||[]);setPos(p.data||[]);setDocs(d.data||[]);const e=l.error||q.error||i.error||p.error||d.error;if(e)setNotice(e.message)}
 useEffect(()=>{load()},[])
 const run=async(fn:()=>Promise<any>,ok:string,after?:()=>void)=>{setBusy(true);setNotice('');try{await fn();setNotice(ok);await load();after?.()}catch(e:any){setNotice(e?.message||'Action failed')}finally{setBusy(false)}}
 const uploadAndLearn=async(file:File)=>{setBusy(true);setNotice(`Saving ${file.name} and teaching TALA…`);try{const result:any=await uploadCommercialDocument(file,'other');const learning=result?.learning;const review=learning?.humanReviewRequired?' Human review required for uncertain fields.':'';setNotice(`TALA learned ${learning?.lines??0} line items from ${learning?.documentType??'document'}${learning?.reference?` ${learning.reference}`:''}.${review}`);await load()}catch(e:any){setNotice(e?.message||'Document upload or learning failed')}finally{setBusy(false)}}
 const submitQuote=async(d:QuoteDraft)=>run(()=>createQuoteWorkflow(d),'Quotation saved with line items',()=>{setQuoteOpen(false);setTab('Quotes')})
 const approve=async(q:any)=>run(async()=>{if(q.tax_treatment==null){const{error}=await supabase.from('quotes').update({tax_treatment:'NONE',tax_rate_basis_points:0}).eq('id',q.id);if(error)throw error}return approveQuoteWorkflow(q.id)},'Quotation approved')
 const printQuote=async(q:any)=>{const{data,error}=await supabase.from('quote_lines').select('*').eq('quote_id',q.id).order('line_no');if(error)return setNotice(error.message);printCommercialDocument({number:q.quote_number||'DRAFT',kind:'QUOTATION',customer:q.customer_name||'',project:q.project_name||'',location:q.location,status:q.status,currency:q.currency,terms:q.terms,leadTime:q.lead_time,subtotalCentavos:q.subtotal_centavos||0,taxCentavos:q.tax_centavos||0,totalCentavos:q.total_centavos||0,lines:data||[]})}
 const printInvoice=async(i:any)=>{const{data,error}=await supabase.from('invoice_lines').select('*').eq('invoice_id',i.id).order('line_no');if(error)return setNotice(error.message);printCommercialDocument({number:i.invoice_number||'DRAFT',kind:'INVOICE',customer:i.customer_name||'',project:i.project_name||'',status:i.status,currency:i.currency,terms:i.terms,subtotalCentavos:i.subtotal_centavos||0,taxCentavos:i.tax_centavos||0,totalCentavos:i.total_centavos||0,balanceCentavos:i.balance_centavos||0,lines:data||[]})}
 const due=invoices.reduce((s,x)=>s+Number(x.balance_centavos||0),0),pipeline=quotes.reduce((s,x)=>s+Number(x.total_centavos||0),0)
 return <div className={`min-h-screen bg-[#f6f8fb] text-[#14263d] lg:grid ${agentOpen?'lg:grid-cols-[238px_minmax(0,1fr)_365px]':'lg:grid-cols-[238px_minmax(0,1fr)]'}`}>
 <aside className="hidden min-h-screen flex-col bg-[#071a30] p-4 text-white lg:flex"><div className="border-b border-[#20344c] px-3 py-4 text-xl font-bold">Azarraga Glass</div><div className="px-3 pb-2 pt-6 text-[9px] font-bold tracking-[.18em] text-[#617891]">COMMERCIAL WORKSPACE</div><nav className="space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>setTab(n)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${tab===n?'bg-[#102d50] text-white':'text-[#9bacc0]'}`}><I size={17}/>{n}</button>)}</nav><div className="mt-auto border-t border-[#20344c] pt-4"><button onClick={()=>setAgentOpen(true)} className="flex items-center gap-3 p-2"><Bot size={18}/><span className="text-left"><b className="block text-xs">Azarraga Agent</b><small className="text-[#77d6ae]">● Connected</small></span></button><button onClick={()=>supabase.auth.signOut()} className="mt-2 flex items-center gap-2 p-2 text-xs text-slate-400"><LogOut size={14}/>Sign out</button></div></aside>
 <section className="min-w-0 p-4 sm:p-8"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><span className="text-[9px] font-extrabold tracking-[.16em] text-[#3972ae]">AZARRAGA COMMERCIAL AGENT / {tab.toUpperCase()}</span><h1 className="mt-1 text-3xl font-bold">{tab}</h1></div><div className="flex gap-2"><button onClick={load} className="rounded-lg border bg-white p-2"><RefreshCw size={17}/></button><button onClick={()=>setAgentOpen(!agentOpen)} className="inline-flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm font-semibold"><Sparkles size={16}/>Agent</button><button disabled={busy} onClick={()=>setQuoteOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-[#0b5daf] px-4 py-2 text-sm font-semibold text-white"><Plus size={16}/>New quote</button></div></header>{notice&&<div className="mb-3 flex items-center justify-between rounded-lg border bg-white px-4 py-3 text-sm"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
 {tab==='Overview'&&<><div className="flex min-h-[185px] flex-col justify-between rounded-2xl bg-gradient-to-br from-[#0b2543] to-[#0d3b69] p-8 text-white sm:flex-row sm:items-end"><div><span className="text-xs font-bold tracking-widest text-[#83b8ed]">AZARRAGA GLASS & ALUMINUM</span><h2 className="mt-3 text-3xl font-bold">Commercial workspace</h2><p className="mt-2 text-[#b8c7d8]">Find the customer. Quote the job. Get paid.</p></div><div className="mt-8 flex items-center gap-3 sm:mt-0"><MapPin/><div><b className="block">Palawan operations</b><span className="text-xs text-[#9db1c7]">Puerto Princesa · El Nido · San Vicente / Port Barton</span></div></div></div><div className="my-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Active leads" value={String(leads.length)} meta="Palawan opportunities"/><Stat label="Quotes in pipeline" value={peso(pipeline)} meta={`${quotes.length} quotations`}/><Stat label="Receivables" value={peso(due)} meta={`${invoices.length} billing records`}/><Stat label="Documents" value={String(docs.length)} meta="Commercial files"/></div><div className="grid gap-3 xl:grid-cols-[1.7fr_1fr]"><Panel title="Needs your attention">{leads.slice(0,4).map(l=><Row key={l.id} icon={Building2} title={l.project||'Opportunity'} sub={`${l.location||'Palawan'} · ${l.next_action||'Review next action'}`} end={`${l.score||0}% fit`}/>)}{!leads.length&&<Empty text="No leads yet."/>}</Panel><Panel title="What are we doing?"><Quick icon={Search} title="Find new business" sub="Add and qualify opportunities" onClick={()=>setModal({type:'lead'})}/><Quick icon={FileText} title="Prepare a quotation" sub="Build a real multi-line quotation" onClick={()=>setQuoteOpen(true)}/><Quick icon={ReceiptText} title="Manage billing" sub="Invoices, payments and balances" onClick={()=>setTab('Invoices')}/><Quick icon={Bot} title="Ask the agent" sub="Use live commercial memory" onClick={()=>setAgentOpen(true)}/></Panel></div></>}
 {tab==='Leads'&&<Page title="Palawan lead pipeline" text="Capture opportunities and move them toward plans and quotation." action={<button onClick={()=>setModal({type:'lead'})} className="primary"><Plus size={16}/>Add lead</button>}><Table heads={['Opportunity','Location','Type','Stage','Next action','Fit']} rows={leads.map(l=>[l.project||'—',l.location||'—',l.project_type||'—',l.status||'—',l.next_action||'—',`${l.score||0}%`])}/></Page>}
 {tab==='Quotes'&&<Page title="Quotation workspace" text="Create, approve, print, receive PO and invoice from one commercial record." action={<button onClick={()=>setQuoteOpen(true)} className="primary"><Plus size={16}/>New quote</button>}><div className="space-y-3">{quotes.map(q=><div key={q.id} className="flex flex-wrap items-center gap-3 rounded-xl border bg-white p-5"><div className="min-w-[190px] flex-1"><b>{q.quote_number||'Draft'}</b><small className="block text-slate-500">{q.customer_name} · {q.project_name}</small></div><strong>{peso(q.total_centavos)}</strong><Badge>{q.status}</Badge><button onClick={()=>printQuote(q)} className="action"><Printer size={15}/>Print</button>{q.status!=='APPROVED'?<button disabled={busy} onClick={()=>approve(q)} className="action"><CheckCircle2 size={15}/>Approve</button>:<><button disabled={busy||pos.some(p=>p.quote_id===q.id)} onClick={()=>setModal({type:'po',q})} className="action"><ShoppingCart size={15}/>{pos.some(p=>p.quote_id===q.id)?'PO received':'Receive PO'}</button><button disabled={busy||invoices.some(i=>i.quote_id===q.id)} onClick={()=>run(()=>createInvoiceWorkflow(q.id,pos.find(p=>p.quote_id===q.id)?.id),'Invoice drafted',()=>setTab('Invoices'))} className="primary">Draft invoice</button></>}</div>)}{!quotes.length&&<Empty text="No quotations yet."/>}</div></Page>}
 {tab==='Invoices'&&<Page title="Invoices & payments" text="Print invoices, record collections and track the remaining balance."><div className="space-y-3">{invoices.map(i=><div key={i.id} className="flex flex-wrap items-center gap-3 rounded-xl border bg-white p-5"><div className="min-w-[190px] flex-1"><b>{i.invoice_number||'Draft'}</b><small className="block text-slate-500">{i.customer_name} · {i.project_name}</small></div><div><small className="block text-slate-500">Balance</small><strong>{peso(i.balance_centavos)}</strong></div><Badge>{i.status}</Badge><button onClick={()=>printInvoice(i)} className="action"><Printer size={15}/>Print</button><button disabled={busy||Number(i.balance_centavos)<=0} onClick={()=>setModal({type:'payment',i})} className="primary">Record payment</button></div>)}{!invoices.length&&<Empty text="No invoices yet."/>}</div></Page>}
 {tab==='Documents'&&<Page title="TALA document learning" text="Upload a PO, quotation, invoice, receipt or supplier document once. The original file is preserved and TALA learns every legible commercial field and line item." action={<label className={`primary cursor-pointer ${busy?'pointer-events-none opacity-60':''}`}><Upload size={16}/>{busy?'Learning…':'Upload & Learn'}<input type="file" accept="image/*,application/pdf" className="hidden" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];e.currentTarget.value='';if(f)await uploadAndLearn(f)}}/></label>}><div className="mb-4 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-[#24496d]"><b>One upload builds commercial memory.</b><span className="ml-1">TALA preserves the source file, reads the document header, customer/project, every product line, dimensions, glass/frame specifications, hardware, quantities, prices, VAT, logistics, discounts and totals. Uncertain fields are flagged for human review instead of invented.</span></div><Table heads={['File','Learning status','Size','Uploaded']} rows={docs.map(d=>[d.title||'Document',d.category==='needs_review'?'Needs review':d.category&&d.category!=='other'?`Learned · ${String(d.category).replaceAll('_',' ')}`:'Stored',d.file_size?`${Math.round(d.file_size/1024)} KB`:'—',d.created_at?new Date(d.created_at).toLocaleDateString():'—'])}/></Page>}
 </section>{agentOpen&&<Agent onClose={()=>setAgentOpen(false)}/>}<QuoteBuilder open={quoteOpen} busy={busy} onClose={()=>setQuoteOpen(false)} onSubmit={submitQuote}/>{modal&&<ActionModal state={modal} close={()=>setModal(null)} run={run}/>}</div>
}

function ActionModal({state,close,run}:any){const[a,setA]=useState(''),[b,setB]=useState('Palawan'),[c,setC]=useState('');const submit=async()=>{if(state.type==='lead')return run(()=>createLeadWorkflow({project:a,location:b,projectType:c||'Commercial'}),'Lead created',close);if(state.type==='po')return run(()=>createPOWorkflow(state.q.id,a),'PO received',close);if(state.type==='payment')return run(()=>recordPaymentWorkflow(state.i.id,Math.round(Number(a)*100),b||'Bank transfer',c),'Payment recorded',close)};return <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h3 className="text-xl font-bold">{state.type==='lead'?'Add opportunity':state.type==='po'?'Receive purchase order':'Record payment'}</h3><button onClick={close}><X/></button></div>{state.type==='lead'?<><Field label="Project / opportunity" value={a} onChange={setA}/><Field label="Location" value={b} onChange={setB}/><Field label="Project type" value={c} onChange={setC}/></>:state.type==='po'?<Field label="Client PO number" value={a} onChange={setA}/>:<><Field label="Amount (PHP)" value={a} onChange={setA} type="number"/><Field label="Method" value={b} onChange={setB}/><Field label="Reference" value={c} onChange={setC}/></>}<button onClick={submit} className="primary mt-5 w-full justify-center">Save</button></div></div>}
function Agent({onClose}:any){const[msg,setMsg]=useState(''),[reply,setReply]=useState(''),[models,setModels]=useState<any[]>([]),[model,setModel]=useState('openrouter/free'),[busy,setBusy]=useState(false);useEffect(()=>{listAgentModels().then((r:any)=>{setModels(r.models||[]);if(r.models?.[0]?.id)setModel(r.models[0].id)}).catch(()=>setModels([{id:'openrouter/free',name:'OpenRouter Free Router'}]))},[]);const ask=async()=>{if(!msg.trim())return;setBusy(true);try{const r:any=await askAgent({data:{message:msg,model,intent:'general'}});setReply(r.error||r.reply)}catch(e:any){setReply(e.message)}finally{setBusy(false)}};return <aside className="min-h-screen border-l bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#eaf3fc] p-2 text-[#0b5daf]"><Bot/></div><div><b>Azarraga Agent</b><small className="block text-green-600">● Connected to commercial memory</small></div></div><button onClick={onClose}><X size={18}/></button></div><div className="my-5 rounded-xl bg-[#f3f7fb] p-4 text-sm"><b>TALA</b><p className="mt-1 text-slate-600">Ask about customers, product history, specifications, quotations, documents, invoices or Palawan opportunities.</p></div><label className="text-xs font-bold">MODEL</label><select value={model} onChange={e=>setModel(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm">{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>{reply&&<div className="mt-4 whitespace-pre-wrap rounded-xl border p-4 text-sm leading-6">{reply}</div>}<div className="mt-4 flex gap-2"><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Ask TALA…" className="min-h-24 flex-1 rounded-xl border p-3 text-sm"/><button disabled={busy} onClick={ask} className="self-end rounded-lg bg-[#0b5daf] p-3 text-white"><Send size={17}/></button></div></aside>}
function Page({title,text,action,children}:any){return <><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">{title}</h2><p className="text-sm text-slate-500">{text}</p></div>{action}</div>{children}</>}
function Panel({title,children}:any){return <div className="rounded-xl border bg-white"><div className="border-b px-5 py-4 font-bold">{title}</div><div>{children}</div></div>}
function Stat({label,value,meta}:any){return <div className="rounded-xl border bg-white p-5"><small className="font-semibold text-slate-500">{label}</small><strong className="mt-2 block text-2xl">{value}</strong><small className="text-slate-400">{meta}</small></div>}
function Row({icon:I,title,sub,end}:any){return <div className="flex items-center gap-3 border-b p-4 last:border-0"><div className="rounded-lg bg-slate-100 p-2"><I size={17}/></div><div className="flex-1"><b className="text-sm">{title}</b><small className="block text-slate-500">{sub}</small></div><b className="text-xs">{end}</b><ChevronRight size={15}/></div>}
function Quick({icon:I,title,sub,onClick}:any){return <button onClick={onClick} className="flex w-full items-center gap-3 border-b p-4 text-left last:border-0 hover:bg-slate-50"><I size={17}/><span className="flex-1"><b className="block text-sm">{title}</b><small className="text-slate-500">{sub}</small></span><ChevronRight size={15}/></button>}
function Table({heads,rows}:any){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#f7f9fb] text-xs text-slate-500"><tr>{heads.map((h:string)=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r:any[],i:number)=><tr key={i} className="border-t">{r.map((v,j)=><td key={j} className="px-5 py-4">{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty text="Nothing here yet."/>}</div>}
function Empty({text}:any){return <div className="p-8 text-center text-sm text-slate-400">{text}</div>}
function Badge({children}:any){return <span className="rounded-full bg-[#e9f2fb] px-3 py-1 text-xs font-bold text-[#1c5f9b]">{children}</span>}
function Field({label,value,onChange,type='text'}:any){return <label className="mt-3 block text-xs font-bold text-slate-600">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 block w-full rounded-lg border p-3 text-sm font-normal"/></label>}
