import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
function isNewSupabaseApiKey(value:string){return value.startsWith('sb_publishable_')||value.startsWith('sb_secret_')}
function createSupabaseFetch(key:string):typeof fetch{return(input,init)=>{const headers=new Headers(typeof Request!=='undefined'&&input instanceof Request?input.headers:undefined);if(init?.headers)new Headers(init.headers).forEach((v,k)=>headers.set(k,v));if(isNewSupabaseApiKey(key)&&headers.get('Authorization')===`Bearer ${key}`)headers.delete('Authorization');headers.set('apikey',key);return fetch(input,{...init,headers})}}
function env(name:string,viteName:string){const p=typeof process!=='undefined'?(process.env?.[name]||process.env?.[viteName]):undefined;if(p)return p;return ((import.meta as any)?.env?.[viteName]||(import.meta as any)?.env?.[name]) as string|undefined}
export const requireSupabaseAuth=createMiddleware({type:'function'})
 .client(async({next})=>{const{supabase}=await import('./client');const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Unauthorized: sign in to Azarraga first');return next({headers:{Authorization:`Bearer ${session.access_token}`}})})
 .server(async({next})=>{const url=env('SUPABASE_URL','VITE_SUPABASE_URL'),key=env('SUPABASE_PUBLISHABLE_KEY','VITE_SUPABASE_PUBLISHABLE_KEY');if(!url||!key)throw new Error('Supabase environment is not available to the server runtime.');const request=getRequest(),auth=request?.headers?.get('authorization');if(!auth?.startsWith('Bearer '))throw new Error('Unauthorized: no Supabase session');const token=auth.slice(7);const supabase=createClient<Database>(url,key,{global:{fetch:createSupabaseFetch(key),headers:{Authorization:`Bearer ${token}`}},auth:{storage:undefined,persistSession:false,autoRefreshToken:false}});const{data,error}=await supabase.auth.getClaims(token);if(error||!data?.claims?.sub)throw new Error('Unauthorized: invalid Supabase session');return next({context:{supabase,userId:data.claims.sub,claims:data.claims}})})
